config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home', as: "home"
  
  get '/index', to: 'moussaillons#index', as: "index"

  get '/show', to: 'moussaillons#show', as: "show"

  get '/edit', to: 'moussaillons#edit', as: "edit"

  get '/new', to: 'moussaillons#new', as: "new"
  
  resources :corsairs
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/moussaillons_controller.rb
class MoussaillonsController < ApplicationController
  
  def index
  	@corsairs = Corsair.all
  end

  def show
  	@corsair = Corsair.find(params[:id])
  end

  def edit
  end

  def new
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moussaillons_helper.rb
module MoussaillonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",  home_path %></li>
        <li><%= link_to "Index des moussaillons",   index_path %></li>
        <li><%= link_to "Nouveau moussaillon", new_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpMoussaillons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
  	<%= render  'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/moussaillons/edit.html.erb
<h1>Moussaillons#edit</h1>
<p>Find me in app/views/moussaillons/edit.html.erb</p>

app/views/moussaillons/index.html.erb
<br><br><br><br><h1>Article</h1>

<% @corsairs.each do |corsair| %>

  <h2><%= corsair.age %></h2>

  <h2><%= corsair.first_name %></h2>
  
  <h2><%= corsair.likeness %></h2>

  <a href="<% corsair_path(corsair.id) %>" class="btn btn-primary">Consulter</a>
 

<% end %>

app/views/moussaillons/new.html.erb
<br>
<br>
<br>
<br>
<br>


<%= form_for :person do |f| %>
  First name: <%= f.text_field :first_name %><br/><br/>
  Petit mot : <%= f.text_area :biography %><br />
  Kebab?    : <%= f.check_box :admin %><br />
  Hoummous?    : <%= f.check_box :admin %><br />
  
<% end %>

app/views/moussaillons/show.html.erb
<h1><%= @corsair.first_name %></h1>


<p><%= @corsair.age %></p>

<p><%= @corsair.likeness %></p>

<p>
<a href="<%= corsairs_path %>" class="btn btn-primary">Revenir aux articles</a>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to 'Enregistre-toi', new_path, class: "btn btn-lg btn-primary" %>
</div>